# -*- coding: utf-8 -*-
"""coustomer churn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FwIxlNYuyDoZJMzjmMYyObUGpeY1dkCb
"""

import pandas as pd
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
print("shape of the dataset ")
print(df.shape)
print("\n first 5 rows ")
print(df.head())
print("\n columns names ")
print(df.columns.tolist())
print("\n datatypes")
print(df.dtypes)
print("\n basic statastics")
print(df.describe())

print("missing values per column ")
print(df.isnull().sum())
print("\n unique  values in target (churn)")
print(df['Churn'].value_counts())
print("\n churn prepotions ")
print(df['Churn'].value_counts(normalize=True).round(3))
print("\n checking total charges column")
print(df['TotalCharges'].dtype)
print(df['TotalCharges'].head(10))

df['totalcharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
print("data type after conversion")
print(df['totalcharges'].dtype)
print("\n missing values after conversion ")
print(df.isnull().sum()[df.isnull().sum()>0])
print("\n how many rows have missing total charges")
print(df['totalcharges'].isnull().sum())
print("\n look at the rows with missing total charges ")
print(df[df['totalcharges'].isnull()][['customerID','tenure','MonthlyCharges','totalcharges']])





from google.colab import files

print("Please select the 'WA_Fn-UseC_-Telco-Customer-Churn.csv' file to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# Move the uploaded file to the /content/ directory if it's not already there
import os
if 'WA_Fn-UseC_-Telco-Customer-Churn.csv' in uploaded and not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
    with open('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', 'wb') as f:
        f.write(uploaded['WA_Fn-UseC_-Telco-Customer-Churn.csv'])
    print("File moved to /content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
else:
    print("File already exists in /content/ or was not uploaded correctly.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Re-initializing df and applying prior transformations to resolve NameError
import pandas as pd
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df['totalcharges']=df['totalcharges'].fillna(0)
print("missing values after fix ")
print(df.isnull().sum().sum())
print("(should be 0)")
# The original code has 'churn' as target column, but df['Churn'] was used in previous cells.
# Assuming 'Churn' is the correct column name and converting its values.
df['Churn']=df['Churn'].map({'Yes':1,'No':0})
print("\nChurn after conversion:")
print(df['Churn'].value_counts())
df=df.drop('customerID',axis =1) # Corrected 'coustomer id' to 'customerID'
print("\nShape after dropping customerID:")
print(df.shape)
numerical_cols=df.select_dtypes(
    include=['int64','float64'] # Changed float62 to float64, which is more common
).columns.tolist()
categorical_cols=df.select_dtypes(include=['object']).columns.tolist()
numerical_cols=[c for c in numerical_cols if c!='Churn'] # Corrected 'churn' to 'Churn'
categorical_cols=[c for c in categorical_cols
                  if c!='Churn'] # Corrected 'churn' to 'Churn'

print("\nNumerical features:")
print(numerical_cols)

print("\nCategorical features:")
print(categorical_cols)

print(f"\nTotal numerical   : {len(numerical_cols)}")
print(f"Total categorical : {len(categorical_cols)}")
print("\nUnique values per categorical feature:")
for col in categorical_cols:
  unique_vals=df[col].unique()
  print(f"\n{col}:")
  print(f"  {unique_vals}")

from google.colab import files

print("Please select the 'WA_Fn-UseC_-Telco-Customer-Churn.csv' file to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# Move the uploaded file to the /content/ directory if it's not already there
import os
if 'WA_Fn-UseC_-Telco-Customer-Churn.csv' in uploaded and not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
    with open('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', 'wb') as f:
        f.write(uploaded['WA_Fn-UseC_-Telco-Customer-Churn.csv'])
    print("File moved to /content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
else:
    print("File already exists in /content/ or was not uploaded correctly.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

print("Please select the 'WA_Fn-UseC_-Telco-Customer-Churn.csv' file to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# Move the uploaded file to the /content/ directory if it's not already there
import os
if 'WA_Fn-UseC_-Telco-Customer-Churn.csv' in uploaded and not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
    with open('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', 'wb') as f:
        f.write(uploaded['WA_Fn-UseC_-Telco-Customer-Churn.csv'])
    print("File moved to /content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
else:
    print("File already exists in /content/ or was not uploaded correctly.")


# Re-initializing df and applying prior transformations
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

fig,axes=plt.subplots(1,2,figsize=(10,4)) # Fixed figsize syntax
sns.countplot(data=df,x='Churn',palette=['steelblue','coral'], ax=axes[0]) # Fixed missing comma and parenthesis, and 'churn' to 'Churn'
axes[0].set_title('Churn count') # Fixed typo set_titale to set_title, and 'churn' to 'Churn'
axes[0].set_xlabel('Churn (0=No, 1=Yes)') # Fixed 'n0' to 'No', and 'churn' to 'Churn'
axes[0].set_ylabel('Count')

churn_props=df['Churn'].value_counts(normalize=True ).sort_index() # Fixed 'churn' to 'Churn'
axes[1].bar(churn_props.index,churn_props.values,color=['steelblue','coral'],edgecolor='white',width=0.4) # Fixed 'axis' to 'axes', and 'color' syntax
axes[1].set_title('Churn proportion') # Fixed indentation and 'churn' to 'Churn'
axes[1].set_xlabel('Churn (0=No, 1=Yes)') # Fixed 'churn' to 'Churn'
axes[1].set_ylabel('Proportion')
axes[1].set_xticks([0,1]) # Fixed typo set_xtricks to set_xticks
axes[1].set_ylim(0,1)
plt.tight_layout()
plt.show()

print("Churn distribution:")
print(df['Churn'].value_counts())
print("\nProportions:")
print(df['Churn'].value_counts(normalize=True).round(3))

# Correcting the numerical column plotting part
# From the previous cell, numerical_cols = ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'totalcharges']
# Assuming the intention was to plot 'tenure', 'MonthlyCharges', 'totalcharges'
hist_numerical_cols=['tenure','MonthlyCharges','totalcharges'] # Create a new list for these plots
fig,axes=plt.subplots(1,3,figsize=(15,4)) # Fixed figsize syntax

for i, col in enumerate(hist_numerical_cols): # Use i and col from enumerate
  df[df['Churn']==0][col].plot( # Fixed 'churn' to 'Churn'
      kind='hist',bins=30,alpha =0.6,color='steelblue',label='No Churn',ax=axes[i] # Fixed 'apha' to 'alpha', extra space in color, and label capitalization
  )
  df[df['Churn']==1][col].plot( # Added plot for Churned customers
      kind='hist',bins=30,alpha =0.6,color='coral',label='Churned',ax=axes[i] # Added plot for Churned customers
  )
  axes[i].set_title(f'{col} by Churn') # Fixed 'cols' to 'col', and 'churn' to 'Churn'
  axes[i].set_xlabel(col)
  axes[i].set_ylabel('Count')
  axes[i].legend()
plt.tight_layout() # Moved plt.tight_layout() and plt.show() outside the loop
plt.show()

print("\nNumerical features by Churn:")
print(df.groupby('Churn')[hist_numerical_cols].mean().round(2)) # Used hist_numerical_cols

plt.figure(figsize=(8,4)) # Fixed figsize syntax
sns.countplot(data=df,x='Contract',hue='Churn',palette=['steelblue','coral']) # Fixed 'churn' to 'Churn', and 'palette' syntax. Also 'contract' to 'Contract' for consistency.
plt.title('Churn by Contract Type') # Fixed 'churn' to 'Churn'
plt.xlabel("Contract Type") # Fixed capitalization
plt.ylabel('Count')
plt.legend(title='Churn',labels=['No Churn','Churned']) # Fixed capitalization
plt.tight_layout()
plt.show()

print("\nChurn rate by Contract type:")
print(df.groupby('Contract')['Churn'].mean().round(3))

plt.figure(figsize=(8, 4))
sns.countplot(data=df, x='InternetService',
              hue='Churn',
              palette=['steelblue', 'coral'])
plt.title('Churn by Internet Service')
plt.xlabel('Internet Service Type')
plt.ylabel('Count')
plt.legend(title='Churn',
           labels=['No Churn', 'Churned'])
plt.tight_layout()
plt.show()

print("\nChurn rate by Internet Service:")
print(df.groupby('InternetService')['Churn'].mean().round(3))
plt.figure(figsize=(8, 4))
sns.countplot(data=df, x='TechSupport',
              hue='Churn',
              palette=['steelblue', 'coral'])
plt.title('Churn by Tech Support')
plt.xlabel('Tech Support')
plt.ylabel('Count')
plt.legend(title='Churn',
           labels=['No Churn', 'Churned'])
plt.tight_layout()
plt.show()

print("\nChurn rate by Tech Support:")
print(df.groupby('TechSupport')['Churn'].mean().round(3))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Re-initializing df and applying prior transformations to ensure df is defined
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

fig,axes=plt.subplots(1,3,figsize=(15,4))
contract_churn=df.groupby('Contract')['Churn'].mean().round(3)
axes[0].bar(contract_churn.index,contract_churn.values,color=['steelblue', 'coral', 'green'],edgecolor='white')
axes[0].set_title('Churn rate by Contract type')
axes[0].set_xlabel("Contract type")
axes[0].set_ylabel('Churn rate ')
axes[0].set_ylim(0,0.6)
for i , v in enumerate (contract_churn.values):
  axes[0].text(i,v+0.01,f'{v:.1%}',ha='center',fontsize=10)

internet_churn=df.groupby('InternetService')['Churn'].mean().round(3)
axes[1].bar(internet_churn.index,internet_churn.values,color=['steelblue','coral','green'],edgecolor='white')
axes[1].set_title("Churn rate by Internet service ")
axes[1].set_xlabel('Internet service ')
axes[1].set_ylabel("Churn rate ")
axes[1].set_ylim(0,0.6)
for i, v in enumerate(internet_churn.values):
  axes[1].text(i, v + 0.01,
               f'{v:.1%}',
               ha='center',
               fontsize=10)

# Tech support churn rate
tech_churn = df.groupby(
    'TechSupport')['Churn'].mean().round(3)
axes[2].bar(tech_churn.index,
            tech_churn.values,
            color=['steelblue', 'coral', 'green'],
            edgecolor='white')
axes[2].set_title('Churn RATE by Tech Support')
axes[2].set_xlabel('Tech Support')
axes[2].set_ylabel('Churn Rate')
axes[2].set_ylim(0, 0.6)
for i, v in enumerate(tech_churn.values):
    axes[2].text(i, v + 0.01,
                 f'{v:.1%}',
                 ha='center',
                 fontsize=10)

plt.tight_layout()
plt.show()
print("Average totalcharges by Churn status:")
print(df.groupby('Churn')['totalcharges'].describe().round(2))

print("\nMean totalcharges:")
print(df.groupby('Churn')['totalcharges'].mean().round(2))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
import os

# Ensure the file is present before reading
if not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
    print("Please select the 'WA_Fn-UseC_-Telco-Customer-Churn.csv' file to upload:")
    uploaded = files.upload()
    for fn in uploaded.keys():
        print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')
    # Move the uploaded file to the /content/ directory if it's not already there
    if 'WA_Fn-UseC_-Telco-Customer-Churn.csv' in uploaded and not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
        with open('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', 'wb') as f:
            f.write(uploaded['WA_Fn-UseC_-Telco-Customer-Churn.csv'])
        print("File moved to /content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
    else:
        print("File already exists in /content/ or was not uploaded correctly.")

# Re-initializing df and applying prior transformations
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
categorical_to_plot = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']

for i, col in enumerate(categorical_to_plot):
  row = i // 3
  col_pos = i % 3
  churn_rate = df.groupby(col)['Churn'].mean().round(3)
  bars = axes[row][col_pos].bar(
      churn_rate.index.astype(str),
      churn_rate.values,
      color=['steelblue', 'coral', 'green'],
      edgecolor='white')
  axes[row][col_pos].set_title(f'Churn rate by {col}')
  axes[row][col_pos].set_xlabel(col)
  axes[row][col_pos].set_ylabel('Churn Rate')
  axes[row][col_pos].set_ylim(0, 0.5)
  for j, v in enumerate(churn_rate.values):
    axes[row][col_pos].text(
        j, v + 0.01, f'{v:.1%}', ha='center', fontsize=10)

plt.tight_layout()
plt.show()

print("Churn rates for each feature:")
for col in categorical_to_plot:
    print(f"\n--- {col.upper()} ---")
    print(df.groupby(col)['Churn'].mean().round(3))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
import os

print("Please select the 'WA_Fn-UseC_-Telco-Customer-Churn.csv' file to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# Move the uploaded file to the /content/ directory if it's not already there
if 'WA_Fn-UseC_-Telco-Customer-Churn.csv' in uploaded and not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
    with open('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', 'wb') as f:
        f.write(uploaded['WA_Fn-UseC_-Telco-Customer-Churn.csv'])
    print("File moved to /content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
else:
    print("File already exists in /content/ or was not uploaded correctly.")


# Re-initializing df and applying prior transformations
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

fig, axes = plt.subplots(3, 3, figsize=(18, 14))
categorical_remaining=['MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaymentMethod','Contract']

# Flatten axes array for easier iteration if it's 2D
axes = axes.flatten()

for i, col in enumerate(categorical_remaining):
  # Using 'i' as the index for flattened axes, which works here since we have enough subplots
  if i < len(axes):
    churn_rate = df.groupby(col)['Churn'].mean().round(3)
    axes[i].bar(churn_rate.index.astype(str), churn_rate.values, color=['steelblue','coral','green'], edgecolor='white')
    axes[i].set_title(f'Churn rate by {col}', fontsize=11)
    axes[i].set_xlabel(col, fontsize=9)
    axes[i].set_ylabel('Churn rate', fontsize=9)
    axes[i].set_ylim(0, 0.55)
    axes[i].tick_params(
        axis='x', rotation=15, labelsize=8
    )
    for j, v in enumerate(churn_rate.values):
      axes[i].text(j, v + 0.01, f'{v:.1%}', ha='center', fontsize=9)

plt.tight_layout()
plt.show()

print("Churn rate for remaining features ")
for col in categorical_remaining:
  print(f"\n--- {col.upper()} ---")
  print(df.groupby(col)['Churn'].mean().round(3))

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

print("Please select the 'WA_Fn-UseC_-Telco-Customer-Churn.csv' file to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# Move the uploaded file to the /content/ directory if it's not already there
if 'WA_Fn-UseC_-Telco-Customer-Churn.csv' in uploaded and not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
    with open('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', 'wb') as f:
        f.write(uploaded['WA_Fn-UseC_-Telco-Customer-Churn.csv'])
    print("File moved to /content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
else:
    print("File already exists in /content/ or was not uploaded correctly.")

# Re-initializing df and applying prior transformations to ensure df is defined
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

fig,axes=plt.subplots(3,2,figsize=(12,10))
numerical_features=['tenure','MonthlyCharges', 'totalcharges'] # Corrected 'monthlycharges' to 'MonthlyCharges'

# Only plot the first two for consistency with the 3x2 subplot setup (hist, kde, boxplot for 2 features)
# If more numerical features need to be plotted, the subplot layout needs to be adjusted
numerical_features_to_plot = numerical_features[:2]

for i, col in enumerate(numerical_features_to_plot): # Corrected 'enumurate' to 'enumerate'
  # Histogram plots
  df[df['Churn']==0][col].plot(kind='hist',bins=30,alpha=0.6,color='steelblue',label='No Churn',ax=axes[0][i]) # Corrected 'churn' to 'Churn' and 'steelbue' to 'steelblue', and label capitalization
  df[df['Churn']==1][col].plot(kind='hist',bins=30,alpha=0.6,color='coral',label='Churned',ax=axes[0][i]) # Corrected 'churn' to 'Churn' and label capitalization, added color
  axes[0][i].set_title(f'{col} Distribution by Churn') # Corrected 'sitribution' and 'churn' to 'Churn'
  axes[0][i].set_xlabel(col)
  axes[0][i].set_ylabel('Count')
  axes[0][i].legend()

  # KDE plots
  df[df['Churn']==0][col].plot(kind='kde',color='steelblue',linewidth=2,label='No Churn',ax=axes[1][i]) # Corrected 'churn' to 'Churn', missing comma
  df[df['Churn']==1][col].plot(kind='kde',color='coral',linewidth=2,label='Churned',ax=axes[1][i]) # Corrected 'churn' to 'Churn', label capitalization
  axes[1][i].set_title(f'{col} KDE by Churn') # Corrected 'col kde by churn '
  axes[1][i].set_xlabel(col)
  axes[1][i].set_ylabel('Density')
  axes[1][i].legend()

  # Boxplot plots
  df.boxplot(column=col,by='Churn',ax=axes[2][i],boxprops=dict(color='steelblue'),medianprops=dict(color='coral',linewidth=2)) # Corrected 'churn' to 'Churn', added medianprops for visibility
  axes[2][i].set_title(f'{col} Boxplot by Churn') # Corrected 'boc' and 'churn'
  axes[2][i].set_xlabel('Churn (0=No, 1=Yes)') # Corrected 'churn(0=no,1=yes)'
  axes[2][i].set_ylabel(col)

plt.suptitle('')
plt.tight_layout()
plt.show()

# =============================================
# Summary statistics
# =============================================
print("Summary statistics by Churn:")
for col in numerical_features:
    print(f"\n--- {col.upper()} ---")
    print(df.groupby('Churn')[col].describe().round(2))

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

print("Please select the 'WA_Fn-UseC_-Telco-Customer-Churn.csv' file to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# Move the uploaded file to the /content/ directory if it's not already there
if 'WA_Fn-UseC_-Telco-Customer-Churn.csv' in uploaded and not os.path.exists('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'):
    with open('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', 'wb') as f:
        f.write(uploaded['WA_Fn-UseC_-Telco-Customer-Churn.csv'])
    print("File moved to /content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
else:
    print("File already exists in /content/ or was not uploaded correctly.")

# Re-initializing df and applying prior transformations to ensure df is defined
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn  as sns
import os
from google.colab import files

# Define the expected file path and name
file_path = '/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'
file_name = 'WA_Fn-UseC_-Telco-Customer-Churn.csv'

# Check if the file exists, if not, prompt for upload
if not os.path.exists(file_path):
    print(f"Please select the '{file_name}' file to upload:")
    uploaded = files.upload()

    if uploaded:
        # Find the actual filename uploaded (Colab might rename it if it already exists in the current working directory)
        actual_uploaded_filename = None
        for fn in uploaded.keys():
            if file_name in fn: # Check if the expected name is part of the uploaded filename
                actual_uploaded_filename = fn
                break

        if actual_uploaded_filename:
            # Move the uploaded file to the /content/ directory with the correct name
            with open(file_path, 'wb') as f:
                f.write(uploaded[actual_uploaded_filename])
            print(f"File '{actual_uploaded_filename}' moved and renamed to '{file_path}'")
        else:
            print("The expected file was not found among the uploaded files.")
    else:
        print("No file was uploaded.")
else:
    print(f"File '{file_name}' already exists at '{file_path}'. Skipping upload.")

# Re-initializing df and applying prior transformations to ensure df is defined

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from google.colab import files

# Define the expected file path and name (copied from LCyR6SOUt6OJ)
file_path = '/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'

df = pd.read_csv(file_path)
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

df_encoded=pd.get_dummies(df,drop_first=True)
print("shape after encoding ")
print(df_encoded.shape)
print("columns after encoding")
print(df_encoded.columns.tolist())
churn_corr=df_encoded.corr()['Churn'].drop('Churn') # Changed 'churn' to 'Churn'
churn_corr_sorted=churn_corr.abs().sort_values(ascending=False)
print(" correlation with churn ")
print(churn_corr.reindex(churn_corr_sorted.index).round(3)) # Removed .round(3) from index as it should be applied to values
top_features=churn_corr_sorted.head(15).index.tolist()
top_features.append('Churn') # Changed 'churn' to 'Churn'
plt.figure(figsize=(14,10))
sns.heatmap(df_encoded[top_features].corr(),annot=True,fmt='.2f',cmap='coolwarm',center=0,vmin=-1,vmax=1,linewidth=0.5,square=True) # Changed 'centre' to 'center'
plt.title('correlation heatmap -top 15 features vs  churn ',
fontsize=13 )
plt.tight_layout()
plt.show()
plt.figure(figsize=(12,8))
colors=['coral'if x>0 else'steelblue' for x in churn_corr.reindex(churn_corr_sorted.index)] # Fixed 'churn_corr_sorted_index' to 'churn_corr_sorted.index'
plt.barh(churn_corr_sorted.index,
         churn_corr.reindex(churn_corr_sorted.index),color=colors,edgecolor='white')
plt.axvline(x=0, color='black',linewidth=0.8,linestyle='--')
plt.axvline(x=0.1,
            color='green',
            linewidth=0.8,
            linestyle='--',
            label='0.1 threshold')

plt.axvline(x=-0.1,
            color='green',
            linewidth=0.8,
            linestyle='--')

plt.title(
    'Feature Correlation with Churn',
    fontsize=13)
plt.xlabel('Correlation Coefficient')
plt.ylabel('Feature')
plt.legend()
plt.tight_layout()
plt.show()

# =============================================
# STEP 5 - check multicollinearity
# =============================================

print("\nMulticollinearity Check:")
print("Correlation between TotalCharges, tenure, MonthlyCharges:")
print(df_encoded[['tenure',
                   'MonthlyCharges',
                   'totalcharges']].corr().round(3)) # Changed 'TotalCharges' to 'totalcharges' as 'TotalCharges' is object type

import pandas as pd
import os
from google.colab import files

# Define the expected file path and name
file_path = '/content/WA_Fn-UseC_-Telco-Customer-Churn.csv'
file_name = 'WA_Fn-UseC_-Telco-Customer-Churn.csv'

# Ensure the file exists (copied from LCyR6SOUt6OJ for robustness if executed independently)
if not os.path.exists(file_path):
    print(f"Please select the '{file_name}' file to upload:")
    uploaded = files.upload()
    if uploaded:
        actual_uploaded_filename = None
        for fn in uploaded.keys():
            if file_name in fn:
                actual_uploaded_filename = fn
                break
        if actual_uploaded_filename:
            with open(file_path, 'wb') as f:
                f.write(uploaded[actual_uploaded_filename])
            print(f"File '{actual_uploaded_filename}' moved and renamed to '{file_path}'")
        else:
            print("The expected file was not found among the uploaded files.")
    else:
        print("No file was uploaded.")
else:
    print(f"File '{file_name}' already exists at '{file_path}'. Skipping upload.")

# Re-initialize df and apply prior transformations (copied from ImxTI4KbniOM)
df = pd.read_csv(file_path)
df['totalcharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})
df = df.drop('customerID',axis =1)

# Ensure the original 'TotalCharges' (object type) column is dropped
# before one-hot encoding the *other* categorical columns.
# This check is crucial as `get_dummies` will encode it otherwise, leading to many columns.
if 'TotalCharges' in df.columns:
    df = df.drop('TotalCharges', axis=1)

# Now encode ONLY the actual categorical columns
categorical_cols_to_encode = ['gender', 'Partner',
                               'Dependents', 'PhoneService',
                               'MultipleLines',
                               'InternetService',
                               'OnlineSecurity',
                               'OnlineBackup',
                               'DeviceProtection',
                               'TechSupport',
                               'StreamingTV',
                               'StreamingMovies',
                               'Contract',
                               'PaperlessBilling',
                               'PaymentMethod']

df_encoded = pd.get_dummies(df,
                             columns=categorical_cols_to_encode,
                             drop_first=True)

print("Shape after correct encoding:")
print(df_encoded.shape)
print("\nColumns:")
print(df_encoded.columns.tolist())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# =============================================
# STEP 1 - ensure correct dtypes first
# (Removed redundant and erroneous conversion of 'TotalCharges' as it was handled previously)
# =============================================

# =============================================
# STEP 2 - encode ONLY categorical text columns
# =============================================

categorical_cols_to_encode = ['gender', 'Partner',
                               'Dependents',
                               'PhoneService',
                               'MultipleLines',
                               'InternetService',
                               'OnlineSecurity',
                               'OnlineBackup',
                               'DeviceProtection',
                               'TechSupport',
                               'StreamingTV',
                               'StreamingMovies',
                               'Contract',
                               'PaperlessBilling',
                               'PaymentMethod']

df_encoded = pd.get_dummies(df,
                             columns=categorical_cols_to_encode,
                             drop_first=True)

print("\nShape after correct encoding:")
print(df_encoded.shape)

# =============================================
# STEP 3 - correlation with Churn
# =============================================

churn_corr = df_encoded.corr()['Churn'].drop('Churn')
churn_corr_sorted = churn_corr.abs().sort_values(
    ascending=False)

print("\nTop 20 correlations with Churn:")
print(churn_corr.reindex(
    churn_corr_sorted.index).head(20).round(3))

# =============================================
# STEP 4 - heatmap (top 15 only)
# =============================================

top_features = churn_corr_sorted.head(15).index.tolist()
top_features.append('Churn')

plt.figure(figsize=(14, 10))
sns.heatmap(df_encoded[top_features].corr(),
            annot=True,
            fmt='.2f',
            cmap='coolwarm',
            center=0,
            vmin=-1,
            vmax=1,
            linewidths=0.5,
            square=True)
plt.title('Correlation Heatmap — Top 15 Features vs Churn')
plt.tight_layout()
plt.show()

# =============================================
# STEP 5 - bar chart (now readable!)
# =============================================

top_20_features = churn_corr_sorted.head(20).index.tolist()
top_20_corr = churn_corr.reindex(top_20_features)

colors = ['coral' if x > 0 else 'steelblue'
          for x in top_20_corr]

plt.figure(figsize=(10, 8))
plt.barh(top_20_corr.index,
         top_20_corr.values,
         color=colors,
         edgecolor='white')
plt.axvline(x=0, color='black',
            linewidth=0.8, linestyle='--')
plt.axvline(x=0.1, color='green',
            linewidth=0.8, linestyle='--',
            label='0.1 threshold')
plt.axvline(x=-0.1, color='green',
            linewidth=0.8, linestyle='--')
plt.title('Top 20 Features — Correlation with Churn')
plt.xlabel('Correlation Coefficient')
plt.legend()
plt.tight_layout()
plt.show()

# =============================================
# STEP 6 - multicollinearity check
# =============================================

print("\nMulticollinearity check:")
print("TotalCharges correlations:")
print(df_encoded[['tenure',
                   'MonthlyCharges',
                   'totalcharges']].corr().round(3)) # Corrected 'TotalCharges' to 'totalcharges'